### ISSUE TITLE
Use autoconf to run configure.ac

### ISSUE THREAD

**Issue by dfordivam** [hasufell/lzma-static#8]
As discussed here https://github.com/haskell/ghcup-hs/issues/707#issuecomment-2408595587

**Comment by dfordivam** [comment]
I will give this a try; with inspiration from https://github.com/vmchale/libarchive/pull/35

**Comment by hasufell** [comment]
I don't think we should commit the `configure` file to the repo. All files that are generated by `autoreconf -fi` should not be committed. But they should be part of the cabal sdist.
